package CalcApp;


/**
* CalcApp/Calc.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, June 25, 2025 8:57:25 PM NPT
*/

public interface Calc extends CalcOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Calc
